-- 1. Create CUSTOMERS Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    CITY VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(20),
    LOYALTY_POINTS NUMBER
);

-- 2. Create ORDERS Table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10, 2),
    DISCOUNT_AMT NUMBER(10, 2),  -- Can be NULL if no discount
    SHIPPING_DATE DATE           -- Can be NULL if not shipped yet
);

-- 3. Insert Data with intentional NULL values
-- Customers
INSERT INTO CUSTOMERS VALUES (101, 'John', 'Doe', 'New York', '555-0100', 500);
INSERT INTO CUSTOMERS VALUES (102, 'Jane', 'Smith', NULL, '555-0101', 120);
INSERT INTO CUSTOMERS VALUES (103, 'Robert', 'Brown', 'Chicago', NULL, 0);
INSERT INTO CUSTOMERS VALUES (104, 'Emily', 'Davis', NULL, NULL, NULL);
INSERT INTO CUSTOMERS VALUES (105, 'Michael', 'Wilson', 'Miami', '555-0105', NULL);

-- Orders
INSERT INTO ORDERS VALUES (5001, 101, DATE '2023-10-01', 150.00, 10.00, DATE '2023-10-03');
INSERT INTO ORDERS VALUES (5002, 102, DATE '2023-10-02', 200.50, NULL, DATE '2023-10-05');
INSERT INTO ORDERS VALUES (5003, 101, DATE '2023-10-05', 75.00, 5.00, NULL);
INSERT INTO ORDERS VALUES (5004, 104, DATE '2023-10-06', 300.00, NULL, NULL);
INSERT INTO ORDERS VALUES (5005, 105, DATE '2023-10-07', 50.00, 0.00, DATE '2023-10-08');
INSERT INTO ORDERS VALUES (5006, NULL, DATE '2023-10-08', 20.00, NULL, DATE '2023-10-09');

COMMIT;

-- 1. Inner Join: Customers with orders that have a discount
SELECT C.FIRST_NAME, O.TOTAL_AMOUNT
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.DISCOUNT_AMT IS NOT NULL;

-- 2. Left Join: All customers with order date if exists
SELECT C.FIRST_NAME, O.ORDER_DATE
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- 3. Right Join: All orders including orphan orders
SELECT O.ORDER_ID, C.FIRST_NAME
FROM CUSTOMERS C
RIGHT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- 4. Full Outer Join: Count rows returned
SELECT COUNT(*)
FROM CUSTOMERS C
FULL OUTER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- 5. Left Join Anti Join: Customers with no orders
SELECT C.CUSTOMER_ID
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;

-- 6. Self Join: Orders placed on same date
SELECT O1.ORDER_ID, O2.ORDER_ID, O1.ORDER_DATE
FROM ORDERS O1
JOIN ORDERS O2 ON O1.ORDER_DATE = O2.ORDER_DATE
AND O1.ORDER_ID < O2.ORDER_ID;

-- 7. Cross Join: Every customer paired with every city
SELECT C.FIRST_NAME, X.CITY
FROM CUSTOMERS C
CROSS JOIN (SELECT DISTINCT CITY FROM CUSTOMERS WHERE CITY IS NOT NULL) X;

-- 8. Inner Join + Aggregates: Total discount for New York customers
SELECT SUM(O.DISCOUNT_AMT) AS total_discount
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.CITY = 'New York';

-- 9. Left Join + NVL: Shipping date or 'Not Shipped'
SELECT C.FIRST_NAME, NVL(TO_CHAR(O.SHIPPING_DATE), 'Not Shipped') AS ship_status
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- 10. Right Join: Sum of orphan orders
SELECT SUM(O.TOTAL_AMOUNT) AS orphan_sales
FROM CUSTOMERS C
RIGHT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

-- 11. Natural Join: Last name and total amount
SELECT LAST_NAME, TOTAL_AMOUNT
FROM CUSTOMERS
NATURAL JOIN ORDERS;

-- 12. Left Join with condition: Only orders > 100
SELECT C.FIRST_NAME, O.ORDER_ID, O.TOTAL_AMOUNT
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
AND O.TOTAL_AMOUNT > 100;

-- 13. Inner Join: Customers with phone numbers
SELECT C.FIRST_NAME, O.ORDER_ID
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.PHONE_NUMBER IS NOT NULL;

-- 14. Full Join + COALESCE: Show IDs
SELECT COALESCE(C.CUSTOMER_ID, O.ORDER_ID) AS ID
FROM CUSTOMERS C
FULL OUTER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- 15. Self Join: Customers with same loyalty points
SELECT C1.CUSTOMER_ID, C2.CUSTOMER_ID, C1.LOYALTY_POINTS
FROM CUSTOMERS C1
JOIN CUSTOMERS C2 ON C1.LOYALTY_POINTS = C2.LOYALTY_POINTS
AND C1.CUSTOMER_ID < C2.CUSTOMER_ID;

-- 16. Inner Join: Shipped orders
SELECT C.FIRST_NAME, C.CITY, O.ORDER_DATE
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.SHIPPING_DATE IS NOT NULL;

-- 17. Left Join: Average order per customer
SELECT C.CUSTOMER_ID, AVG(O.TOTAL_AMOUNT) AS avg_order
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID;

-- 18. Cross Join: Count rows generated
SELECT COUNT(*)
FROM CUSTOMERS
CROSS JOIN ORDERS;

-- 19. Join with date comparison: Orders placed after shipping date
SELECT O.ORDER_ID, O.ORDER_DATE, O.SHIPPING_DATE
FROM ORDERS O
WHERE O.ORDER_DATE > O.SHIPPING_DATE;

-- 20. Three-way simulation: Customers with more than one order
SELECT C.CUSTOMER_ID, COUNT(O.ORDER_ID) AS order_count
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
HAVING COUNT(O.ORDER_ID) > 1;